jobs:
  verify:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./ci/run

name: Check

on:
  schedule:
    - cron: "15 0/3 * * *"
